[versions]
agp = "8.11.2"
kotlin = "2.0.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.1"
composeBom = "2024.09.00"

datastore-preferences-core = "1.1.1"
datastore-preferences = "1.1.1"

navigation-compose="2.8.4"
timber = "5.0.1"
chucker-library = "4.0.0"
chucker-library-no-op = "4.0.0"
google-services = "4.4.0"
devtools-ksp = "2.0.21-1.0.27"
kotlinx-serialization-json  = "1.7.3"
kotlinx-serialization-converter = "1.0.0"

hilt-android = "2.52"
hilt-navigation-compose = "1.2.0"
hilt-android-compiler = "2.52"
composeMaterialIcons = "1.7.6"
retrofit = "2.11.0"
converter-moshi = "2.11.0"
logging-interceptor = "4.12.0"
kotlin-coroutines-adapter =  "0.9.2"
moshi-kotlin-codegen  = "1.15.1"
moshi-lazy-adapters  = "2.2"
moshi-kotlin  = "1.15.1"
coil = "2.6.0"
foundation = "1.10.0"
room = "2.6.1"
sqlite = "2.4.0"
sqlcipher-android = "4.6.1"


[libraries]
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended", version.ref = "composeMaterialIcons" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }

hilt-android = { group = "com.google.dagger",name = "hilt-android",version.ref = "hilt-android"}
hilt-navigation-compose = { group ="androidx.hilt",name = "hilt-navigation-compose", version.ref = "hilt-navigation-compose"}
hilt-android-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt-android-compiler" }

logging-interceptor= { group ="com.squareup.okhttp3",name = "logging-interceptor", version.ref = "logging-interceptor"}
converter-moshi = {group ="com.squareup.retrofit2",name = "converter-moshi", version.ref = "converter-moshi" }
kotlin-coroutines-adapter = { group = "com.jakewharton.retrofit",name = "retrofit2-kotlin-coroutines-adapter", version.ref = "kotlin-coroutines-adapter"}
moshi-kotlin-codegen = { group ="com.squareup.moshi",name = "moshi-kotlin-codegen", version.ref = "moshi-kotlin-codegen"}
moshi-lazy-adapters = {group = "com.serjltt.moshi", name = "moshi-lazy-adapters", version.ref = "moshi-lazy-adapters"}
moshi-kotlin = {group = "com.squareup.moshi", name = "moshi-kotlin", version.ref = "moshi-kotlin"}

retrofit = { group = "com.squareup.retrofit2",name = "retrofit",version.ref = "retrofit"}
kotlinx-serialization-converter = {group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version.ref = "kotlinx-serialization-converter"}
kotlinx-serialization-json = {group = "org.jetbrains.kotlinx",name ="kotlinx-serialization-json", version.ref = "kotlinx-serialization-json"}

chucker-library = { group = "com.github.chuckerteam.chucker", name = "library", version.ref = "chucker-library"}
chucker-library-no-op = { group = "com.github.chuckerteam.chucker", name = "library-no-op",version.ref = "chucker-library-no-op"}

navigation-compose = {group = "androidx.navigation",name = "navigation-compose", version.ref = "navigation-compose"}
timber = {group = "com.jakewharton.timber",name = "timber", version.ref= "timber"}
coil-compose = { group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
datastore-preferences-core = { group = "androidx.datastore",name = "datastore-preferences-core" ,version.ref = "datastore-preferences-core"}
datastore-preferences = {group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore-preferences"}
androidx-foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }
room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-sqlite = { group = "androidx.sqlite", name = "sqlite", version.ref = "sqlite" }
sqlcipher-android = { group = "net.zetetic", name = "sqlcipher-android", version.ref = "sqlcipher-android" }
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }


google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "devtools-ksp" }
dagger-hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt-android" }
kotlin-plugin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version = "1.8.0" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }